config/routes.rb
Rails.application.routes.draw do


resources :users
resources :organisms
resources :walks

get '/signup', to: 'users#new', as: 'signup'
get '/signin', to: 'sessions#new'
post '/signin', to: 'sessions#create'
get '/signout', to: 'sessions#destroy'
get '/users/:id/delete_profile', to: 'users#destroy',as: 'delete_profile'


root to: 'welcome#index'


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :walks
  has_many :organisms, through: :walks
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment :image,
  content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
  has_secure_password
  validates :password, presence: true, :on => :create

  def add_to_nature_lover_level
    self.nature_lover_level += 1
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 
  before_action :authorize, except: [:new, :create, :welcome]

  helper_method :current_user, :logged_in, :authorize


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def logged_in?
      !!session[:user_id]
  end

  def authorize
      redirect_to root_path unless logged_in?
  end

end

app/controllers/organism_controller.rb
class OrganismController < ApplicationController
  def index
    @organisms = Organism.all
  end

  def new
    @organism = Organism.new
  end

  def create
    @organism = Organism.create(organism_params)
  end

  def show
    @organism = Organism.find(params[:id])
  end

  def delete
  end

  private
    def organism_params
      params.require(:organims).permit(:species,:group,:location)
    end
end

app/controllers/organisms_controller.rb
class OrganismsController < ApplicationController
  def index
    @organisms = Organism.all
  end

  def new
    @organism = Organism.new
  end

  def create
      @organism = Organism.find_by(species: params[:organism][:species])
        if @organism == nil
          @organism = Organism.create(organism_params)
          walk_user = User.find(current_user)
          walk_user.add_to_nature_lover_level
          walk_user.save
          @organism.users << walk_user
          @organism.save
          redirect_to organism_path(@organism)
        else
          walk_user = User.find(current_user)
          walk_user.add_to_nature_lover_level
          walk_user.save
          @organism.users << walk_user
          @organism.save
          redirect_to organism_path(@organism)
        end
      end

  def show
    @organism = Organism.find(params[:id])
  end

  def delete
  end

  private
    def organism_params
      params.require(:organism).permit(:species,:location)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
      @user = User.new
  end

  def create
      @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
          session[:user_id] = @user.id
          redirect_to user_path(@user)
      else
          flash[:notice] = 'username or password not correct'
          redirect_to signin_path

      end
  end

  def destroy
      session[:user_id] = nil
      redirect_to '/'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:show, :edit, :update, :destroy]
before_action :require_login, only: [:show,:destroy]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
      else
          render 'new'
      end
  end

  def show
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to user_path(@user)
      else
        render 'edit'
      end
    end

  def destroy
    if @user.id == session[:user_id]
    @user.destroy
    redirect_to new_user_path
    else
      redirect_to new_user_path
  end
  end

  private
    def user_params
      params.require(:user).permit(:name, :password, :location, :nature_lover_level, :username, :interest,:image)
    end
    def require_login
      redirect_to '/' unless session.include? :user_id
    end

    def set_user
        @user = User.find(params[:id])
    end

end

app/controllers/walk_controller.rb
class WalkController < ApplicationController
  def index
  end

  def new
    @walk = Walk.new
  end

  def create
    @walk=Walk.create(organism_id:params[:organism_id], user_id:params[:user_id])
  end

  def show
    @walk = Walk.find(:id)
  end

  def delete
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    
  def index

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Social Media for Nature Lovers</title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
  </head>
  <body>
    <!--  navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
           <!--  nav here -->
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>

  </body>
</html>

app/views/organisms/_organism.html.erb
<strong> <%= link_to "Click on group #{organism.group}", organism_path(organism) %></strong><br/>

app/views/organisms/delete.html.erb
<h1>Organism#delete</h1>
<p>Find me in app/views/organism/delete.html.erb</p>

app/views/organisms/index.html.erb
<h1>Choose a group of organisms</h1>
<% @organisms.each do |organism| %>
<%= link_to organism.group %>
<% end  %>

app/views/organisms/new.html.erb
<%= stylesheet_link_tag "organism" %>

<h1> NatureWalk </h1>

<div class="form">
<%= form_for(@organism) do|f| %>

<p>What did you see?</p>
<%= f.text_field :species %></br></br>
<p>Where did you see it?</p>
<%= f.text_field :location%></br></br>
<%= f.submit "Submit Walk"%>

<% end %>

</div>

app/views/organisms/show.html.erb
<h1><%= @organism.species %></h1>

<strong>Sighting Location:</strong> <%= @organism.location.capitalize %><br/><br>

<strong>User's that spotted <%= @organism.species %></strong></br>

<% @organism.users.each do |user| %>
<%= link_to user.name, user_path(user) %><br>
<% end  %>

app/views/users/edit.html.erb
<h1>Edit your user profile</h1>

<%= form_for @user do |f| %>
<%= f.label :name%>
<%= f.text_field :name %><br/>
<%= f.label :username %>
<%= f.text_field :username %></br>
<%= f.label :password%>
<%= f.password_field :password %><br/>
<%= f.label :location%>
<%= f.text_field :location %><br/>
<%= f.label :interest %>
<%= f.text_field :interest %></br>
<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<%= stylesheet_link_tag "user" %>

<div id="links_on_director">
<h1>NatureGo Directory</h1>
<table>


<% @users.each do |user| %>
  <div><%= link_to user.name, user_path(user) %></div>
  <%= user.interest%><br>
<% end %>
</table>
</div>

app/views/users/new.html.erb
<%= stylesheet_link_tag "user" %>

<div class="form">
<h1>Sign Up</h1>

<%= form_for @user, url: users_path, html: { multipart: true } do |f| %>
<%= f.label :name%>
<%= f.text_field :name %><br/>
<%= f.label :username %>
<%= f.text_field :username %></br>
<%= f.label :password%>
<%= f.password_field :password %><br/>
<%= f.label :location%>
<%= f.text_field :location %><br/>
<%= f.label :interest %>
<%= f.text_field :interest %></br>
<%= f.label :profile_pic %>
<%= f.file_field :image %>

<%= f.submit %>
<% end %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag "user" %>
<h1> Welcome <%= @user.username %>!</h1>

<img class="img-circle" <%= image_tag @user.image.url(:medium) %>><br>

<p style="color: black; font-size: 16px">Location: <%= @user.location %> <br>
Interests: <%= @user.interest %> <br>

Nature Lover Level: <%= @user.nature_lover_level %><br><br></p>


<div id="links_on_org">
<h3>Sightings:</h3>
<% @user.organisms.each do |organism| %>
<li style="color: black; font-size: 16px"><%= link_to organism.species, organism_path(organism), id: "links_on_org" %> -
  <%= organism.location%>
  <%= organism.created_at.strftime("on %m/%d/%Y") %></li>
<% end  %><br>



<%= link_to 'Take a walk' , new_organism_path, id: "links_on_org"  %><br><br>
  <%= link_to 'Edit your profile', edit_user_path, id: "links_on_org"  %><br>
  <%= link_to 'Delete your profile', delete_profile_path, id: "links_on_org"   %><br>
<%= link_to 'Sign Out' , signout_path, id: "links_on_org"  %><br>
</div>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag "welcome" %>




<h1>Welcome to Nature Go!</h1></br>

<div class="tag_line">
<p><em>A networking site for nature lovers</em></p>
</div>

</br>

<div id="link_welcome_page">
<%= link_to "Sign Up", signup_path, id: "link_welcome_page" %></br>
<%= link_to "Sign In", signin_path, id: "link_welcome_page"  %></br>
<%= link_to "See Who's On Nature Go", users_path, id: "link_welcome_page"   %>

</div>